### ISSUE TITLE
This doesn't work.

### ISSUE THREAD

**Issue by yyms3275** [ChenZihan-sudo/Youtube-AD-blocker#1]
This doesn't work....

**Comment by catcolia** [comment]
Hello, I have no problems with my personal use. If it is convenient, can you provide me why it doesn't work and attach me a photo in console  when you open youtube. Please also check if adblocker is open.

**Comment by catcolia** [comment]
You can update it in greasyfork and check if it works now :)

**Comment by yyms3275** [comment]
> You can update it in greasyfork and check if it works now :)

Thank you. I'll check it out.
